
package com.sap.xi.basis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommunicationChannelIn", targetNamespace = "http://sap.com/xi/BASIS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sap.xi.basis.ObjectFactory.class,
    com.sap.xi.basis.global.ObjectFactory.class
})
public interface CommunicationChannelIn {


    /**
     * 
     * @param communicationChannelCheckRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection check(
        @WebParam(name = "CommunicationChannelCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCheckRequest")
        CommunicationChannelIdentifierCollection communicationChannelCheckRequest);

    /**
     * 
     * @param communicationChannelQueryRequest
     * @return
     *     returns com.sap.xi.basis.CommunicationChannelQueryOut
     */
    @WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "CommunicationChannelQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelQueryResponse")
    public CommunicationChannelQueryOut query(
        @WebParam(name = "CommunicationChannelQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelQueryRequest")
        CommunicationChannelQueryIn communicationChannelQueryRequest);

    /**
     * 
     * @param communicationChannelRevertRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection revert(
        @WebParam(name = "CommunicationChannelRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelRevertRequest")
        CommunicationChannelIdentifierCollection communicationChannelRevertRequest);

    /**
     * 
     * @param communicationChannelCreateRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut create(
        @WebParam(name = "CommunicationChannelCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCreateRequest")
        CommunicationChannelCreateChangeIn communicationChannelCreateRequest);

    /**
     * 
     * @param communicationChannelChangeRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut change(
        @WebParam(name = "CommunicationChannelChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelChangeRequest")
        CommunicationChannelCreateChangeIn communicationChannelChangeRequest);

    /**
     * 
     * @param communicationChannelCreateFromTemplateRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "CreateFromTemplate", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut createFromTemplate(
        @WebParam(name = "CommunicationChannelCreateFromTemplateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCreateFromTemplateRequest")
        CommunicationChannelCreateFromTemplateIn communicationChannelCreateFromTemplateRequest);

    /**
     * 
     * @param communicationChannelOpenForEditRequest
     * @return
     *     returns com.sap.xi.basis.CommunicationChannelOpenForEditOut
     */
    @WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "CommunicationChannelOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelOpenForEditResponse")
    public CommunicationChannelOpenForEditOut openForEdit(
        @WebParam(name = "CommunicationChannelOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelOpenForEditRequest")
        CommunicationChannelDeleteOpenForEditIn communicationChannelOpenForEditRequest);

    /**
     * 
     * @param communicationChannelReadRequest
     * @return
     *     returns com.sap.xi.basis.CommunicationChannelReadOut
     */
    @WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "CommunicationChannelReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelReadResponse")
    public CommunicationChannelReadOut read(
        @WebParam(name = "CommunicationChannelReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelReadRequest")
        CommunicationChannelReadIn communicationChannelReadRequest);

    /**
     * 
     * @param communicationChannelDeleteRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut delete(
        @WebParam(name = "CommunicationChannelDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelDeleteRequest")
        CommunicationChannelDeleteOpenForEditIn communicationChannelDeleteRequest);

}
