
package com.sap.xi.basis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommunicationChannelInService", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "file:/C:/Users/i321257/Documents/PIDocTool/src/CommunicationChannelInImplBean.wsdl")
public class CommunicationChannelInService
    extends Service
{

    private final static URL COMMUNICATIONCHANNELINSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMUNICATIONCHANNELINSERVICE_EXCEPTION;
    private final static QName COMMUNICATIONCHANNELINSERVICE_QNAME = new QName("http://sap.com/xi/BASIS", "CommunicationChannelInService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/i321257/Documents/PIDocTool/src/CommunicationChannelInImplBean.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMUNICATIONCHANNELINSERVICE_WSDL_LOCATION = url;
        COMMUNICATIONCHANNELINSERVICE_EXCEPTION = e;
    }

    public CommunicationChannelInService() {
        super(__getWsdlLocation(), COMMUNICATIONCHANNELINSERVICE_QNAME);
    }

    public CommunicationChannelInService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMUNICATIONCHANNELINSERVICE_QNAME, features);
    }

    public CommunicationChannelInService(URL wsdlLocation) {
        super(wsdlLocation, COMMUNICATIONCHANNELINSERVICE_QNAME);
    }

    public CommunicationChannelInService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMUNICATIONCHANNELINSERVICE_QNAME, features);
    }

    public CommunicationChannelInService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommunicationChannelInService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommunicationChannelIn
     */
    @WebEndpoint(name = "CommunicationChannelInPort")
    public CommunicationChannelIn getCommunicationChannelInPort() {
        return super.getPort(new QName("http://sap.com/xi/BASIS", "CommunicationChannelInPort"), CommunicationChannelIn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommunicationChannelIn
     */
    @WebEndpoint(name = "CommunicationChannelInPort")
    public CommunicationChannelIn getCommunicationChannelInPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sap.com/xi/BASIS", "CommunicationChannelInPort"), CommunicationChannelIn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMUNICATIONCHANNELINSERVICE_EXCEPTION!= null) {
            throw COMMUNICATIONCHANNELINSERVICE_EXCEPTION;
        }
        return COMMUNICATIONCHANNELINSERVICE_WSDL_LOCATION;
    }

}
