
package com.sap.xi.basis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegratedConfigurationInService", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "file:/C:/DEV/PI/ID%20Export/workspace/PIDocTool/src/IntegratedConfigurationInImplBean.wsdl")
public class IntegratedConfigurationInService
    extends Service
{

    private final static URL INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRATEDCONFIGURATIONINSERVICE_EXCEPTION;
    private final static QName INTEGRATEDCONFIGURATIONINSERVICE_QNAME = new QName("http://sap.com/xi/BASIS", "IntegratedConfigurationInService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/DEV/PI/ID%20Export/workspace/PIDocTool/src/IntegratedConfigurationInImplBean.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION = url;
        INTEGRATEDCONFIGURATIONINSERVICE_EXCEPTION = e;
    }

    public IntegratedConfigurationInService() {
        super(__getWsdlLocation(), INTEGRATEDCONFIGURATIONINSERVICE_QNAME);
    }

    public IntegratedConfigurationInService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRATEDCONFIGURATIONINSERVICE_QNAME, features);
    }

    public IntegratedConfigurationInService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRATEDCONFIGURATIONINSERVICE_QNAME);
    }

    public IntegratedConfigurationInService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRATEDCONFIGURATIONINSERVICE_QNAME, features);
    }

    public IntegratedConfigurationInService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegratedConfigurationInService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegratedConfigurationIn
     */
    @WebEndpoint(name = "IntegratedConfigurationInPort")
    public IntegratedConfigurationIn getIntegratedConfigurationInPort() {
        return super.getPort(new QName("http://sap.com/xi/BASIS", "IntegratedConfigurationInPort"), IntegratedConfigurationIn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegratedConfigurationIn
     */
    @WebEndpoint(name = "IntegratedConfigurationInPort")
    public IntegratedConfigurationIn getIntegratedConfigurationInPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sap.com/xi/BASIS", "IntegratedConfigurationInPort"), IntegratedConfigurationIn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRATEDCONFIGURATIONINSERVICE_EXCEPTION!= null) {
            throw INTEGRATEDCONFIGURATIONINSERVICE_EXCEPTION;
        }
        return INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION;
    }

}
