
package com.sap.xi.basis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegratedConfigurationIn", targetNamespace = "http://sap.com/xi/BASIS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sap.xi.basis.ObjectFactory.class,
    com.sap.xi.basis.global.ObjectFactory.class
})
public interface IntegratedConfigurationIn {


    /**
     * 
     * @param integratedConfigurationCheckRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection check(
        @WebParam(name = "IntegratedConfigurationCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationCheckRequest")
        IntegratedConfigurationIdentifierCollection integratedConfigurationCheckRequest);

    /**
     * 
     * @param integratedConfigurationChangeRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut change(
        @WebParam(name = "IntegratedConfigurationChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationChangeRequest")
        IntegratedConfigurationCreateChangeIn integratedConfigurationChangeRequest);

    /**
     * 
     * @param integratedConfigurationQueryRequest
     * @return
     *     returns com.sap.xi.basis.IntegratedConfigurationQueryOut
     */
    @WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "IntegratedConfigurationQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationQueryResponse")
    public IntegratedConfigurationQueryOut query(
        @WebParam(name = "IntegratedConfigurationQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationQueryRequest")
        IntegratedConfigurationQueryIn integratedConfigurationQueryRequest);

    /**
     * 
     * @param integratedConfigurationCreateRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut create(
        @WebParam(name = "IntegratedConfigurationCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationCreateRequest")
        IntegratedConfigurationCreateChangeIn integratedConfigurationCreateRequest);

    /**
     * 
     * @param integratedConfigurationRevertRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection revert(
        @WebParam(name = "IntegratedConfigurationRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationRevertRequest")
        IntegratedConfigurationIdentifierCollection integratedConfigurationRevertRequest);

    /**
     * 
     * @param integratedConfigurationReadRequest
     * @return
     *     returns com.sap.xi.basis.IntegratedConfigurationReadOut
     */
    @WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "IntegratedConfigurationReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationReadResponse")
    public IntegratedConfigurationReadOut read(
        @WebParam(name = "IntegratedConfigurationReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationReadRequest")
        IntegratedConfigurationReadIn integratedConfigurationReadRequest);

    /**
     * 
     * @param integratedConfigurationDeleteRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut delete(
        @WebParam(name = "IntegratedConfigurationDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationDeleteRequest")
        IntegratedConfigurationDeleteOpenForEditIn integratedConfigurationDeleteRequest);

    /**
     * 
     * @param integratedConfigurationOpenForEditRequest
     * @return
     *     returns com.sap.xi.basis.IntegratedConfigurationOpenForEditOut
     */
    @WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "IntegratedConfigurationOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationOpenForEditResponse")
    public IntegratedConfigurationOpenForEditOut openForEdit(
        @WebParam(name = "IntegratedConfigurationOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationOpenForEditRequest")
        IntegratedConfigurationDeleteOpenForEditIn integratedConfigurationOpenForEditRequest);

}
