
package com.sap.xi.basis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiverRuleIn", targetNamespace = "http://sap.com/xi/BASIS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sap.xi.basis.ObjectFactory.class,
    com.sap.xi.basis.global.ObjectFactory.class
})
public interface ReceiverRuleIn {


    /**
     * 
     * @param receiverRuleCheckRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection check(
        @WebParam(name = "ReceiverRuleCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleCheckRequest")
        ReceiverRuleIdentifierCollection receiverRuleCheckRequest);

    /**
     * 
     * @param receiverRuleChangeRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut change(
        @WebParam(name = "ReceiverRuleChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleChangeRequest")
        ReceiverRuleCreateChangeIn receiverRuleChangeRequest);

    /**
     * 
     * @param receiverRuleQueryRequest
     * @return
     *     returns com.sap.xi.basis.ReceiverRuleQueryOut
     */
    @WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ReceiverRuleQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleQueryResponse")
    public ReceiverRuleQueryOut query(
        @WebParam(name = "ReceiverRuleQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleQueryRequest")
        ReceiverRuleQueryIn receiverRuleQueryRequest);

    /**
     * 
     * @param receiverRuleCreateRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut create(
        @WebParam(name = "ReceiverRuleCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleCreateRequest")
        ReceiverRuleCreateChangeIn receiverRuleCreateRequest);

    /**
     * 
     * @param receiverRuleRevertRequest
     * @return
     *     returns com.sap.xi.basis.LogMessageCollection
     */
    @WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
    public LogMessageCollection revert(
        @WebParam(name = "ReceiverRuleRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleRevertRequest")
        ReceiverRuleIdentifierCollection receiverRuleRevertRequest);

    /**
     * 
     * @param receiverRuleReadRequest
     * @return
     *     returns com.sap.xi.basis.ReceiverRuleReadOut
     */
    @WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ReceiverRuleReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleReadResponse")
    public ReceiverRuleReadOut read(
        @WebParam(name = "ReceiverRuleReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleReadRequest")
        ReceiverRuleReadIn receiverRuleReadRequest);

    /**
     * 
     * @param receiverRuleDeleteRequest
     * @return
     *     returns com.sap.xi.basis.ConfigurationObjectModifyOut
     */
    @WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
    public ConfigurationObjectModifyOut delete(
        @WebParam(name = "ReceiverRuleDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleDeleteRequest")
        ReceiverRuleDeleteOpenForEditIn receiverRuleDeleteRequest);

    /**
     * 
     * @param receiverRuleOpenForEditRequest
     * @return
     *     returns com.sap.xi.basis.ReceiverRuleOpenForEditOut
     */
    @WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ReceiverRuleOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleOpenForEditResponse")
    public ReceiverRuleOpenForEditOut openForEdit(
        @WebParam(name = "ReceiverRuleOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleOpenForEditRequest")
        ReceiverRuleDeleteOpenForEditIn receiverRuleOpenForEditRequest);

}
